"""Add timestamp to items

Revision ID: e5b93e5c5683
Revises: 28d9d712ca58
Create Date: 2024-05-30 00:27:46.926656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b93e5c5683'
down_revision = '28d9d712ca58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_item', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
